### ISSUE TITLE
Runtime info and framework compatibility matrix are incompatible

### ISSUE THREAD

**Issue by xellDart** [ArianK16a/android_kernel_xiaomi_sm6150#5]
Hi, I build the kernel with crdroid 13 sources for toco, using this propetary vendors (https://github.com/xiaomi-sm6150), but i get

The following HALs in device manifest are not declared in FCM <= level 4: 
  android.hardware.audio.effect@6.0::IEffectsFactory/default
  android.hardware.audio@6.0::IDevicesFactory/default
  android.hardware.biometrics.fingerprint@2.3::IBiometricsFingerprint/default
  android.hardware.bluetooth.audio@2.1::IBluetoothAudioProvidersFactory/default
  android.hardware.cas@1.2::IMediaCasService/default
  android.hardware.drm.IDrmFactory/clearkey (@1)
  android.hardware.drm@1.3::ICryptoFactory/widevine
  android.hardware.drm@1.3::IDrmFactory/widevine
  android.hardware.health@2.1::IHealth/default
  android.hardware.keymaster@4.1::IKeymasterDevice/default
  android.hardware.power.IPower/default (@2)
  android.hardware.radio@1.5::IRadio/slot1
  android.hardware.radio@1.5::IRadio/slot2
  android.hardware.vibrator.IVibrator/default (@2)
  android.hardware.wifi.hostapd.IHostapd/default (@1)
  android.hardware.wifi.supplicant.ISupplicant/default (@1)
  android.hardware.wifi@1.6::IWifi/default
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 5).
For kernel requirements at matrix level 5, For config CONFIG_DEBUG_FS, value = y but required n
: Success
INCOMPATIBLE

How I can fix this?

**Comment by ArianK16a** [comment]
This kernel is not being used anymore, please refer to the fork on GitHub.com/LineageOS
